Repository airavata-courses/SuperNova, pull requests merged in 2022-02, with the labels that each got.

#53 HighLevelArchitecture
  wiki/wiki_images/Project1-HighLevelArchitecture.pdf
Labels: documentation

#51 Added user session service
  .gitignore
  Project1-WeatherRadar/weather-radar-ui/src/app/dashboard/dashboard.component.ts
  Project1-WeatherRadar/weather-radar-ui/src/app/modal/user-session-info.ts
  Project1-WeatherRadar/weather-radar-ui/src/app/user.service.ts
Labels: enhancement

#50 Restructuring Changes
  weather-radar-ui/.angular/cache/13.1.4/angular-webpack/a0820b021d260f517d8c4607c59994fc69d5d029/0.pack
  weather-radar-ui/.angular/cache/13.1.4/angular-webpack/a0820b021d260f517d8c4607c59994fc69d5d029/index.pack
Labels: enhancement

#55 Removing-ui-files
  Project1-WeatherRadar/weather-radar-ui/.browserslistrc
  Project1-WeatherRadar/weather-radar-ui/.editorconfig
  Project1-WeatherRadar/weather-radar-ui/.gitignore
  Project1-WeatherRadar/weather-radar-ui/.vscode/extensions.json
  Project1-WeatherRadar/weather-radar-ui/.vscode/launch.json
  Project1-WeatherRadar/weather-radar-ui/.vscode/tasks.json
  Project1-WeatherRadar/weather-radar-ui/README.md
  Project1-WeatherRadar/weather-radar-ui/angular.json
  Project1-WeatherRadar/weather-radar-ui/karma.conf.js
  Project1-WeatherRadar/weather-radar-ui/package-lock.json
  Project1-WeatherRadar/weather-radar-ui/package.json
  Project1-WeatherRadar/weather-radar-ui/src/app/app-routing.module.ts
  Project1-WeatherRadar/weather-radar-ui/src/app/app.component.html
  Project1-WeatherRadar/weather-radar-ui/src/app/app.component.scss
  Project1-WeatherRadar/weather-radar-ui/src/app/app.component.spec.ts
  Project1-WeatherRadar/weather-radar-ui/src/app/app.component.ts
  Project1-WeatherRadar/weather-radar-ui/src/app/app.module.ts
  Project1-WeatherRadar/weather-radar-ui/src/app/auth-guard.service.ts
  Project1-WeatherRadar/weather-radar-ui/src/app/dashboard/dashboard.component.html
  Project1-WeatherRadar/weather-radar-ui/src/app/dashboard/dashboard.component.scss
  Project1-WeatherRadar/weather-radar-ui/src/app/dashboard/dashboard.component.spec.ts
  Project1-WeatherRadar/weather-radar-ui/src/app/dashboard/dashboard.component.ts
  Project1-WeatherRadar/weather-radar-ui/src/app/login/login.component.html
  Project1-WeatherRadar/weather-radar-ui/src/app/login/login.component.scss
  Project1-WeatherRadar/weather-radar-ui/src/app/login/login.component.spec.ts
  Project1-WeatherRadar/weather-radar-ui/src/app/login/login.component.ts
  Project1-WeatherRadar/weather-radar-ui/src/app/modal/rad-station.ts
  Project1-WeatherRadar/weather-radar-ui/src/app/modal/user-session-info.ts
  Project1-WeatherRadar/weather-radar-ui/src/app/user.service.spec.ts
  Project1-WeatherRadar/weather-radar-ui/src/app/user.service.ts
  Project1-WeatherRadar/weather-radar-ui/src/app/weather.service.spec.ts
  Project1-WeatherRadar/weather-radar-ui/src/app/weather.service.ts
  Project1-WeatherRadar/weather-radar-ui/src/assets/.gitkeep
  Project1-WeatherRadar/weather-radar-ui/src/assets/loginbg.jpg
  Project1-WeatherRadar/weather-radar-ui/src/environments/environment.prod.ts
  Project1-WeatherRadar/weather-radar-ui/src/environments/environment.ts
  Project1-WeatherRadar/weather-radar-ui/src/favicon.ico
  Project1-WeatherRadar/weather-radar-ui/src/index.html
  Project1-WeatherRadar/weather-radar-ui/src/main.ts
  Project1-WeatherRadar/weather-radar-ui/src/polyfills.ts
  Project1-WeatherRadar/weather-radar-ui/src/styles.scss
  Project1-WeatherRadar/weather-radar-ui/src/test.ts
  Project1-WeatherRadar/weather-radar-ui/tsconfig.app.json
  Project1-WeatherRadar/weather-radar-ui/tsconfig.json
  Project1-WeatherRadar/weather-radar-ui/tsconfig.spec.json
Labels: invalid

#72 Added changes to handle GIF image
  Project1-WeatherRadar/weather-radar-gateway/fakeapi/server.js
  Project1-WeatherRadar/weather-radar-gateway/gateway.js
  Project1-WeatherRadar/weather-radar-gateway/package-lock.json
  Project1-WeatherRadar/weather-radar-gateway/package.json
  Project1-WeatherRadar/weather-radar-gateway/routes/index.js
  Project1-WeatherRadar/weather-radar-gateway/routes/registry.json
Labels: bug

#78 Added weather plot endpoint in cache microservice
  Project1-WeatherRadar/weather-cache/index.js
Labels: enhancement

#80 Query status endpoint implementation
  Project1-WeatherRadar/weather-cache/index.js
  Project1-WeatherRadar/weather-cache/query.js
Labels: enhancement

#87 weather data status in cache
  Project1-WeatherRadar/weather-cache/index.js
  Project1-WeatherRadar/weather-cache/query.js
Labels: enhancement
